

CATEGORY_MAP = {
    # Oscillateurs
    "sine": "oscillators",
    "cosine": "oscillators",
    "square_wave": "oscillators",
    "sawtooth": "oscillators",
    "triangle_wave": "oscillators",
    "multi_sine": "oscillators",
    "am_signal": "oscillators",
    "fm_signal": "oscillators",
    "chirp": "oscillators",
    "damped_oscillator": "oscillators",
    "growing_oscillator": "oscillators",
    "coupled_oscillators": "oscillators",
    "beating": "oscillators",
    "harmonic_series": "oscillators",

    # Tendances
    "linear_trend": "trends",
    "quadratic_trend": "trends",
    "exp_growth": "trends",
    "exp_decay": "trends",
    "logistic_growth": "trends",
    "log_growth": "trends",
    "power_law": "trends",
    "trend_seasonal": "trends",
    "multiplicative_seas": "trends",
    "double_seasonal": "trends",

    # Stochastiques
    "white_noise": "stochastic",
    "ar1": "stochastic",
    "ar2": "stochastic",
    "ma2": "stochastic",
    "arma": "stochastic",
    "random_walk": "stochastic",
    "rw_drift": "stochastic",
    "gbm": "stochastic",
    "ornstein_uhlenbeck": "stochastic",
    "garch": "stochastic",
    "pink_noise": "stochastic",
    "brown_noise": "stochastic",
    "poisson": "stochastic",
    "hawkes": "stochastic",
    "fractional_bm": "stochastic",
    "levy_flight": "stochastic",
    "mixture_gaussian": "stochastic",
    "student_t": "stochastic",

    # Chaotiques
    "lorenz_x": "chaotic",
    "lorenz_z": "chaotic",
    "rossler": "chaotic",
    "van_der_pol": "chaotic",
    "duffing": "chaotic",
    "logistic_map": "chaotic",
    "henon_map": "chaotic",
    "mackey_glass": "chaotic",
    "tent_map": "chaotic",
    "ikeda_map": "chaotic",

    # Physiques / ODE
    "lotka_volterra": "physical_ode",
    "sir_epidemic": "physical_ode",
    "rc_circuit": "physical_ode",
    "spring_mass": "physical_ode",
    "pendulum": "physical_ode",
    "forced_oscillator": "physical_ode",
    "heat_equation": "physical_ode",
    "cir_process": "physical_ode",
    "glycolysis": "physical_ode",
    "brusselator": "physical_ode",
    "fitzhugh_nagumo": "physical_ode",
    "double_well": "physical_ode",

    # Régimes
    "regime_switch_2": "regime_transition",
    "regime_switch_3": "regime_transition",
    "level_shift": "regime_transition",
    "variance_shift": "regime_transition",
    "trend_change": "regime_transition",
    "intermittent": "regime_transition",
    "spike_series": "regime_transition",
    "step_function": "regime_transition",
    "markov_switching": "regime_transition",
    "seasonal_regime": "regime_transition",
    "pulse_train": "regime_transition",
    "ramp_signals": "regime_transition",

    # Réelles simulées
    "electricity": "realistic_simulated",
    "temperature": "realistic_simulated",
    "traffic": "realistic_simulated",
    "financial_returns": "realistic_simulated",
    "stock_price": "realistic_simulated",
    "retail_sales": "realistic_simulated",
    "eeg": "realistic_simulated",
    "ecg": "realistic_simulated",
    "wind_speed": "realistic_simulated",
    "precipitation": "realistic_simulated",
    "cpu_usage": "realistic_simulated",
    "network_traffic": "realistic_simulated",
    "sensor_drift": "realistic_simulated",
    "exchange_rate": "realistic_simulated",
    "pageviews": "realistic_simulated",

    # Mixtures
    "sine_ar": "mixtures",
    "trend_garch": "mixtures",
    "seasonal_regime_sw": "mixtures",
    "lorenz_periodic": "mixtures",
    "multi_scale": "mixtures",
    "rw_mean_revert": "mixtures",
    "noisy_ode": "mixtures",
    "mixed_frequency": "mixtures",
}